storage:
  engine: wiredTiger
  dbPath: /var/lib/mongod/data

systemLog:
  destination: file
  path: /var/log/mongodb/mongod.log
  logAppend: true

net:
  bindIp: 0.0.0.0
  port: 27017

security:
  authorization: enabled

setParameter:
  enableLocalhostAuthBypass: true